services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ~/rabbitmq/helpdesk/data:/var/lib/rabbitmq/
      - ~/rabbitmq/helpdesk/logs:/var/log/rabbitmq
    networks:
      - helpdesk

  config-server:
    image: asterixcode/helpdesk-config-server:latest
    container_name: config-server
    env_file:
      - ./config-server/.env
    ports:
      - "8888:8888"
    expose:
      - "8888"
    networks:
      - helpdesk

  service-discovery:
    image: asterixcode/helpdesk-service-discovery:latest
    container_name: service-discovery
    env_file:
      - ./service-discovery/.env
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - helpdesk
    depends_on:
      - config-server
    links:
      - config-server

networks:
  helpdesk:
    driver: bridge