spring:
  application:
    name: 'order-service-api'
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT}